FC \WORK\A.TXT \WORK\B.TXT > \OUT\FC1.TXT
IF ERRORLEVEL 1 ECHO FC1 1 >> \OUT\EL.TXT
IF NOT ERRORLEVEL 1 ECHO FC1 0 >> \OUT\EL.TXT
FC /B \WORK\A.TXT \WORK\B.TXT > \OUT\FCB.TXT
IF ERRORLEVEL 1 ECHO FCB 1 >> \OUT\EL.TXT
IF NOT ERRORLEVEL 1 ECHO FCB 0 >> \OUT\EL.TXT
FC \WORK\A.TXT \WORK\A.TXT > \OUT\FCSAME.TXT
IF ERRORLEVEL 1 ECHO FCSAME 1 >> \OUT\EL.TXT
IF NOT ERRORLEVEL 1 ECHO FCSAME 0 >> \OUT\EL.TXT
FC /N \WORK\A.TXT \WORK\B.TXT > \OUT\FCN.TXT
FC \T\L1.TXT \T\L2.TXT > \OUT\FCL.TXT
IF ERRORLEVEL 1 ECHO FCL 1 >> \OUT\EL.TXT
IF NOT ERRORLEVEL 1 ECHO FCL 0 >> \OUT\EL.TXT
FC /C \T\L1.TXT \T\L2.TXT > \OUT\FCC.TXT
FC /W \T\L1.TXT \T\L2.TXT > \OUT\FCW.TXT
FC /C/W \T\L1.TXT \T\L2.TXT > \OUT\FCCW.TXT
FC /LB2 \T\R1.TXT \T\R2.TXT > \OUT\FCLB2.TXT
IF ERRORLEVEL 1 ECHO FCLB2 1 >> \OUT\EL.TXT
IF NOT ERRORLEVEL 1 ECHO FCLB2 0 >> \OUT\EL.TXT
FC \T\R1.TXT \T\R2.TXT > \OUT\FCR.TXT
FC \T\M1.TXT \T\M2.TXT > \OUT\FCM.TXT
FC /A \T\M1.TXT \T\M2.TXT > \OUT\FCMA.TXT
FC /N /A \T\M1.TXT \T\M2.TXT > \OUT\FCMNA.TXT
FC \T\A1.TXT \T\A2.TXT > \OUT\FCA1.TXT
FC /3 \T\A1.TXT \T\A2.TXT > \OUT\FCA3.TXT
FC \T\B1.BIN \T\B2.BIN > \OUT\FCBIN.TXT
FC /L \T\B1.BIN \T\B2.BIN > \OUT\FCBINL.TXT
FC \T\P1.EXE \T\P2.EXE > \OUT\FCEXE.TXT
FC /T \T\T1.TXT \T\T2.TXT > \OUT\FCT.TXT
FC \T\T1.TXT \T\T2.TXT > \OUT\FCTAB.TXT
FC \NOFILE.TXT \WORK\A.TXT > \OUT\FCNOF.TXT
IF ERRORLEVEL 1 ECHO FCNOF 1 >> \OUT\EL.TXT
IF NOT ERRORLEVEL 1 ECHO FCNOF 0 >> \OUT\EL.TXT
FC \WORK\A.TXT \NOFILE.TXT > \OUT\FCNOF2.TXT
FC \WORK\A.TXT > \OUT\FCONE.TXT
IF ERRORLEVEL 1 ECHO FCONE 1 >> \OUT\EL.TXT
IF NOT ERRORLEVEL 1 ECHO FCONE 0 >> \OUT\EL.TXT
FC > \OUT\FCNONE.TXT
FC /B /N \WORK\A.TXT \WORK\B.TXT > \OUT\FCBN.TXT
FC /X \WORK\A.TXT \WORK\B.TXT > \OUT\FCX.TXT
FC \WORK\A.TXT/N \WORK\B.TXT > \OUT\FCGLUE.TXT
FC \WORK \WORK\B.TXT > \OUT\FCDIR.TXT
FC \WORK\B.TXT \WORK\A.TXT > \OUT\FCBA.TXT
FC /B \WORK\B.TXT \WORK\A.TXT > \OUT\FCBBA.TXT
ECHO done > \OUT\DONE.TXT
