#!/usr/bin/env node
// apps/tcc/tools/mkhostsyms.mjs - the C library symbols TCC.EXE exports to
// programs it runs with "TCC -run":
//
//   node mkhostsyms.mjs OUT.c [TCC0.elf LIB.a...]
//
// A -run program is linked in memory against TCC.EXE's own copy of libdos /
// newlib / libgcc (one heap, one stdio, one set of DOS handles - a second
// copy of the run-time would fight over the DOS memory block). The table
// lists every global function/object the first link of TCC.EXE (TCC0.elf)
// took from those libraries; with no ELF it is empty (the first link).
import fs from 'node:fs';
import { execFileSync } from 'node:child_process';

const [out, elf, ...libs] = process.argv.slice(2);
const nm = (f) => execFileSync('arm-none-eabi-nm', ['--defined-only', '-g', f], { maxBuffer: 64 << 20 }).toString();
let names = [];
if (elf) {
  const fromLibs = new Set();
  for (const l of libs)
    for (const line of nm(l).split('\n')) {
      const m = line.match(/^[0-9a-f]+ ([TDBRW]) (\S+)$/i);
      if (m) fromLibs.add(m[2]);
    }
  for (const line of nm(elf).split('\n')) {
    const m = line.match(/^[0-9a-f]+ ([TDBRW]) (\S+)$/i);
    if (m && fromLibs.has(m[2]) && /^[A-Za-z_][A-Za-z0-9_]*$/.test(m[2])) names.push(m[2]);
  }
  names = [...new Set(names)].sort();
}
let c = '/* generated by apps/tcc/tools/mkhostsyms.mjs - do not edit */\n';
c += '/* C library symbols of TCC.EXE, for programs run with TCC -run */\n\n';
for (const n of names) c += `extern char ${n}[];\n`;
c += '\nconst struct tcc_armdos_hostsym { const char *name; void *addr; } tcc_armdos_hostsyms[] = {\n';
for (const n of names) c += `    { "${n}", ${n} },\n`;
c += '    { 0, 0 }\n};\n';
fs.writeFileSync(out, c);
console.log(`mkhostsyms: ${names.length} symbols -> ${out}`);
