JOIN > \OUT\J0.TXT
MD \JN
JOIN A: \JN > \OUT\J1.TXT
JOIN > \OUT\J2.TXT
JOIN A: /D > \OUT\J3.TXT
JOIN > \OUT\J4.TXT
JOIN A: \JN2 > \OUT\J5.TXT
JOIN > \OUT\J6.TXT
JOIN A: /D
IF ERRORLEVEL 1 ECHO JE1 >> \OUT\EL.TXT
CLS
JOIN A: \WORK
JOIN C: \JN
JOIN A: \JN\SUB
JOIN A:
JOIN A: /D
JOIN /X
JOIN A: \JN X
JOIN A: \JN /D
JOIN A: C:\
JOIN X: \JN
JOIN A: \JN
JOIN A: \JN
JOIN A: /D
SCRDUMP C:\OUT\ERRORS.SCR
