/* ARM/AT BIOS — INT 10h, the video services, for the ARM-PC VGA, or an MDA /
   Hercules Graphics Card with a monochrome monitor (mode 7 at B0000h, CRTC at
   3B4h; see README.md). Hercules graphics have no BIOS mode: as on
   real PCs, programs program the card themselves.
   Mode 62h is the ARM-PC's 640x480 256-colour mode, one byte per pixel from
   A0000h to EAFFFh (the card decodes the adapter hole in that mode; ARCH.md 6,
   README.md). */
#include "bios.h"

int video_card = VID_VGA;
static uint16_t crtc_port = 0x3D4;

static int is_text(int m) { return m <= 3 || m == 7; }
static int cols_of(int m) { return (m <= 1) ? 40 : (m == 4 || m == 5 || m == 0x13 || m == 0x0D) ? 40 : 80; }
/* the EGA/VGA 16-colour planar modes */
static int is_planar(int m) { return m == 0x0D || m == 0x0E || m == 0x10 || m == 0x12; }
static int planar_h(int m) { return m == 0x12 ? 480 : m == 0x10 ? 350 : 200; }
#define LFB_W 640
#define LFB_H 480
/* character cell height of a graphics mode's teletype text */
static int gfx_cell(int m) { return (m == 0x62 || m == 0x12) ? 16 : m == 0x10 ? 14 : 8; }
static void gc(uint8_t reg, uint8_t v) { outb(0x3CE, reg); outb(0x3CF, v); }

static void crtc(uint8_t reg, uint8_t v) { outb(crtc_port, reg); outb(crtc_port + 1, v); }

int video_mono(void) { return video_card != VID_VGA; }
int video_default_mode(void) { return video_mono() ? 7 : 3; }
int video_is_text(void) { return is_text(BDA8(BDA_VMODE)); }
static volatile uint16_t *text_base(void) { return video_mono() ? MDAMEM : TEXTMEM; }

/* a 6845 answers at `port` if its cursor-address register reads back */
static int crtc_present(uint16_t port)
{
    outb(port, 0x0F);
    uint8_t old = inb(port + 1);
    outb(port + 1, 0x5A);
    int ok = inb(port + 1) == 0x5A;
    outb(port + 1, 0xA5);
    ok = ok && inb(port + 1) == 0xA5;
    outb(port + 1, old);
    return ok;
}

/* Colour CRTC at 3D4h: the VGA. Else a CRTC at 3B4h: a monochrome card, which
   is a Hercules if bit 7 of the status port (vertical retrace) toggles within a
   few frames - the test every Hercules-aware program uses. Needs the timer
   running (POST calls it after irq_enable). */
int video_detect(void)
{
    video_card = VID_VGA;
    crtc_port = 0x3D4;
    if (crtc_present(0x3D4)) return video_card;
    if (!crtc_present(0x3B4)) return video_card;     /* nothing found: assume the VGA */
    video_card = VID_MDA;
    crtc_port = 0x3B4;
    uint8_t first = inb(0x3BA) & 0x80;
    uint32_t t0 = ticks();
    while (ticks() - t0 < 3)
        if ((inb(0x3BA) & 0x80) != first) { video_card = VID_HERCULES; break; }
    return video_card;
}

/* ---------------------------------------------------------- palettes */

/* The VGA's power-on 256-colour palette, as generated by every VGA BIOS:
   16 EGA colours, 16 greys, then 9 blocks of 24-step hue wheels. */
static void dac_default256(void)
{
    static const uint8_t grey[16] = { 0, 5, 8, 11, 14, 17, 20, 24, 28, 32, 36, 40, 45, 50, 56, 63 };
    static const uint8_t ramps[9][5] = {
        { 0, 16, 31, 47, 63 }, { 31, 39, 47, 55, 63 }, { 45, 49, 54, 58, 63 },
        { 0, 7, 14, 21, 28 },  { 14, 17, 21, 24, 28 }, { 20, 22, 24, 26, 28 },
        { 0, 4, 8, 12, 16 },   { 8, 10, 12, 14, 16 },  { 11, 12, 13, 15, 16 },
    };
    outb(0x3C8, 0);
    for (int i = 0; i < 16; i++) {
        int b = (i & 1) ? 42 : 0, g = (i & 2) ? 42 : 0, r = (i & 4) ? 42 : 0;
        if (i == 6) g = 21;
        if (i & 8) { r += 21; g += 21; b += 21; }
        outb(0x3C9, r); outb(0x3C9, g); outb(0x3C9, b);
    }
    for (int i = 0; i < 16; i++) { outb(0x3C9, grey[i]); outb(0x3C9, grey[i]); outb(0x3C9, grey[i]); }
    for (int blk = 0; blk < 9; blk++) {
        const uint8_t *v = ramps[blk];
        uint8_t lo = v[0], hi = v[4];
        for (int k = 0; k < 24; k++) {
            int seg = k / 4, pos = k % 4;
            int r, g, b;
            switch (seg) {
            case 0: r = v[pos]; g = lo; b = hi; break;           /* blue -> magenta */
            case 1: r = hi; g = lo; b = v[4 - pos]; break;       /* magenta -> red */
            case 2: r = hi; g = v[pos]; b = lo; break;           /* red -> yellow */
            case 3: r = v[4 - pos]; g = hi; b = lo; break;       /* yellow -> green */
            case 4: r = lo; g = hi; b = v[pos]; break;           /* green -> cyan */
            default: r = lo; g = v[4 - pos]; b = hi; break;      /* cyan -> blue */
            }
            outb(0x3C9, r); outb(0x3C9, g); outb(0x3C9, b);
        }
    }
    for (int i = 248; i < 256; i++) { outb(0x3C9, 0); outb(0x3C9, 0); outb(0x3C9, 0); }
}

/* The 64-colour EGA palette (rgbRGB) that text and CGA modes use */
static void dac_ega64(void)
{
    outb(0x3C8, 0);
    for (int i = 0; i < 64; i++) {
        int b = ((i & 1) ? 42 : 0) + ((i & 8) ? 21 : 0);
        int g = ((i & 2) ? 42 : 0) + ((i & 16) ? 21 : 0);
        int r = ((i & 4) ? 42 : 0) + ((i & 32) ? 21 : 0);
        outb(0x3C9, r); outb(0x3C9, g); outb(0x3C9, b);
    }
}

static const uint8_t ega_attr[16] = { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x14, 0x07,
                                      0x38, 0x39, 0x3A, 0x3B, 0x3C, 0x3D, 0x3E, 0x3F };

static void attr_write(uint8_t idx, uint8_t v)
{
    if (video_mono()) return;
    (void)inb(0x3DA);           /* reset the flip-flop */
    outb(0x3C0, idx);
    outb(0x3C0, v);
    outb(0x3C0, 0x20);          /* re-enable video */
}

static void attr_palette(const uint8_t *p16)
{
    for (int i = 0; i < 16; i++) attr_write(i, p16[i]);
}

static void set_blink(int on)
{
    if (video_mono()) {         /* the MDA mode control register, bit 5 */
        if (on) BDA8(BDA_CRTMODE) |= 0x20; else BDA8(BDA_CRTMODE) &= ~0x20;
        outb(0x3B8, BDA8(BDA_CRTMODE));
        return;
    }
    uint8_t mc = on ? 0x08 : 0x00;
    attr_write(0x10, mc | 0x04);
    if (on) BDA8(BDA_CRTMODE) |= 0x20; else BDA8(BDA_CRTMODE) &= ~0x20;
}

/* ------------------------------------------------------------- fonts */

static int font_height = 16;
static void text_cell(int h);

void video_load_text_font(void)
{
    for (int c = 0; c < 256; c++)
        for (int r = 0; r < 32; r++)
            FONTRAM[c * 32 + r] = r < 16 ? font8x16[c * 16 + r] : 0;
    font_height = 16;
}

static void load_font8(void)
{
    for (int c = 0; c < 256; c++)
        for (int r = 0; r < 32; r++)
            FONTRAM[c * 32 + r] = r < 8 ? font8x8[c * 8 + r] : 0;
    font_height = 8;
}

/* ------------------------------------------------------------- modes */

static void update_cursor_hw(void)
{
    int page = BDA8(BDA_VPAGE);
    uint16_t pos = BDA16(BDA_CURPOS + page * 2);
    int row = pos >> 8, col = pos & 0xFF;
    int cols = BDA16(BDA_VCOLS);
    uint16_t cell = BDA16(BDA_VPAGESTART) / 2 + row * cols + col;
    crtc(0x0E, cell >> 8);
    crtc(0x0F, cell & 0xFF);
}

void video_cursor_shape(int start, int end)
{
    BDA16(BDA_CURSHAPE) = (start << 8) | end;
    int ch = BDA8(BDA_CHARHEIGHT) ? BDA8(BDA_CHARHEIGHT) : 16;
    /* VGA cursor emulation: a CGA-style shape (lines 0-7) is scaled to the cell
       (an MDA has none: the 6845 gets the lines as given) */
    if (!video_mono() && ch > 8 && !(start & 0x20) && start < 8 && end < 8) {
        if (start == 6 && end == 7) { start = ch - 3; end = ch - 2; }
        else if (end == 7 && start < 6) { start = start * ch / 8; end = ch - 1; }
        else { start = start * ch / 8; end = (end + 1) * ch / 8 - 1; }
    }
    crtc(0x0A, start);
    crtc(0x0B, end);
}

/* text geometry for an 8-, 14- or 16-line character cell (AX=1111h/1112h/1114h) */
static void text_cell(int h)
{
    int rows = 400 / h;
    for (int c = 0; c < 256; c++)
        for (int r = 0; r < 32; r++) {
            uint8_t v = 0;
            if (h == 8) v = r < 8 ? font8x8[c * 8 + r] : 0;
            else if (h == 14) v = r < 14 ? font8x16[c * 16 + r + 1] : 0;
            else v = r < 16 ? font8x16[c * 16 + r] : 0;
            FONTRAM[c * 32 + r] = v;
        }
    font_height = h;
    crtc(0x09, h - 1);
    BDA8(BDA_CHARHEIGHT) = h;
    BDA8(BDA_VROWS) = rows - 1;
    BDA16(BDA_VPAGESIZE) = ((rows * BDA16(BDA_VCOLS) * 2) + 255) & ~255;
    video_cursor_shape(6, 7);
}

void video_cursor_default(void)
{
    if (video_mono()) video_cursor_shape(0x0B, 0x0C);
    else video_cursor_shape(6, 7);
}

/* mode 7 on the MDA / Hercules: the IBM BIOS's 6845 table for 80x25 mono */
static void mda_set_mode(int noclear)
{
    static const uint8_t mda_crtc[16] = { 0x61, 0x50, 0x52, 0x0F, 0x19, 0x06, 0x19, 0x19,
                                          0x02, 0x0D, 0x0B, 0x0C, 0x00, 0x00, 0x00, 0x00 };
    BDA8(BDA_VMODE) = 7;
    BDA16(BDA_VCOLS) = 80;
    BDA8(BDA_VROWS) = 24;
    BDA8(BDA_VPAGE) = 0;
    BDA16(BDA_VPAGESTART) = 0;
    BDA16(BDA_CRTC) = 0x3B4;
    for (int i = 0; i < 8; i++) BDA16(BDA_CURPOS + i * 2) = 0;
    BDA16(BDA_VPAGESIZE) = 4096;
    BDA8(BDA_CRTMODE) = 0x29;               /* high res, video on, blink */
    BDA8(BDA_CGAPAL) = 0x30;
    BDA8(BDA_VIDCTL) = 0;                   /* no EGA */
    BDA8(BDA_CHARHEIGHT) = 14;
    outb(0x3B8, 0x01);                      /* video off while reprogramming (text, page 0) */
    for (int i = 0; i < 16; i++) crtc(i, mda_crtc[i]);
    if (!noclear) for (int i = 0; i < 0x4000; i++) MDAMEM[i] = 0x0720;
    outb(0x3B8, 0x29);
    BDA16(BDA_CURSHAPE) = 0x0B0C;
}

void video_set_mode(int mode)
{
    int noclear = mode & 0x80;
    mode &= 0x7F;
    if (video_mono()) {         /* the IBM BIOS: with a mono card every mode set is mode 7 */
        mda_set_mode(noclear);
        update_cursor_hw();
        return;
    }
    if (!(mode <= 6 || mode == 0x13 || mode == 0x62 || is_planar(mode))) return;

    BDA8(BDA_VMODE) = mode;
    BDA16(BDA_VCOLS) = cols_of(mode);
    BDA8(BDA_VROWS) = mode == 0x62 ? LFB_H / 16 - 1 : mode == 0x12 ? 29 : 24;
    BDA8(BDA_VPAGE) = 0;
    BDA16(BDA_VPAGESTART) = 0;
    BDA16(BDA_CRTC) = 0x3D4;
    for (int i = 0; i < 8; i++) BDA16(BDA_CURPOS + i * 2) = 0;
    /* (mode 62h: 300 KB, more than the word holds) */
    BDA16(BDA_VPAGESIZE) = is_text(mode) ? (cols_of(mode) == 80 ? 4096 : 2048) : (mode == 0x13 ? 64000 : mode == 0x62 ? 0 :
                           is_planar(mode) ? (mode == 0x0D ? 0x2000 : mode == 0x0E ? 0x4000 : mode == 0x10 ? 0x8000 : 0x9600) : 16384);
    BDA8(BDA_CRTMODE) = is_text(mode) ? 0x29 : 0x0A;
    BDA8(BDA_CGAPAL) = mode == 6 ? 0x3F : 0x30;
    BDA8(BDA_VIDCTL) = 0x60;

    if (is_text(mode)) {
        dac_ega64();
        attr_palette(ega_attr);
        set_blink(1);
        video_load_text_font();
        BDA8(BDA_CHARHEIGHT) = 16;
        crtc(0x09, 0x0F);
        crtc(0x0C, 0); crtc(0x0D, 0);
        if (!noclear) for (int i = 0; i < 0x4000; i++) TEXTMEM[i] = 0x0720;
        video_cursor_shape(6, 7);
    } else {
        BDA8(BDA_CHARHEIGHT) = gfx_cell(mode);
        load_font8();
        if (mode == 0x62) {
            dac_default256();
            uint8_t id[16];
            for (int i = 0; i < 16; i++) id[i] = i;
            attr_palette(id);
            /* the frame buffer appears (cleared by the card) when the mode
               register says 62h; clear it again for a real card's sake */
            outb(0x3E0, mode);
            if (!noclear) memset((void *)VGAMEM, 0, LFB_W * LFB_H);
        } else if (is_planar(mode)) {
            if (mode == 0x0D || mode == 0x0E) {
                /* 200-line modes: the attribute palette is 00-07,10-17 and the
                   DAC holds the CGA colours with bit 4 as intensity */
                static const uint8_t pal200[16] = { 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
                                                    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17 };
                outb(0x3C8, 0);
                for (int i = 0; i < 64; i++) {
                    int c = (i & 7) | ((i & 0x10) ? 8 : 0);
                    int b = (c & 1) ? 42 : 0, g = (c & 2) ? 42 : 0, r = (c & 4) ? 42 : 0;
                    if (c == 6) g = 21;
                    if (c & 8) { r += 21; g += 21; b += 21; }
                    outb(0x3C9, r); outb(0x3C9, g); outb(0x3C9, b);
                }
                attr_palette(pal200);
            } else {
                dac_ega64();
                attr_palette(ega_attr);
            }
            /* the card loads the mode's registers (and opens its planar window
               at A0000h) when the mode register says so; then clear all four
               planes through it */
            outb(0x3E0, mode);
            if (!noclear) {
                outb(0x3C4, 2); outb(0x3C5, 0x0F);
                volatile uint32_t *p = (volatile uint32_t *)VGAMEM;
                for (int i = 0; i < 0x10000 / 4; i++) p[i] = 0;
            }
        } else if (mode == 0x13) {
            dac_default256();
            uint8_t id[16];
            for (int i = 0; i < 16; i++) id[i] = i;
            attr_palette(id);
            if (!noclear) memset((void *)VGAMEM, 0, 65536);
        } else {
            dac_ega64();
            attr_palette(ega_attr);
            outb(0x3D9, BDA8(BDA_CGAPAL));
            if (!noclear) memset((void *)CGAMEM, 0, 16384);
        }
        crtc(0x0A, 0x20);   /* no hardware cursor in graphics modes */
    }
    outb(0x3E0, mode);
    update_cursor_hw();
}

/* ---------------------------------------------------------- pixels */

/* planar modes: one bit per plane per pixel; write mode 2 with a one-bit mask
   (bit 7 of the colour: XOR), reads plane by plane through read map select */
static int planar_bpl(void) { return BDA16(BDA_VCOLS); }
static void planar_put(int x, int y, int color)
{
    int m = BDA8(BDA_VMODE);
    if ((unsigned)x >= (unsigned)planar_bpl() * 8 || (unsigned)y >= (unsigned)planar_h(m)) return;
    volatile uint8_t *p = VGAMEM + y * planar_bpl() + (x >> 3);
    outb(0x3C4, 2); outb(0x3C5, 0x0F);
    gc(5, 2); gc(8, 0x80 >> (x & 7)); gc(3, (color & 0x80) ? 0x18 : 0x00);
    (void)*p;                   /* load the latches */
    *p = color & 0x0F;
    gc(3, 0); gc(8, 0xFF); gc(5, 0);
}
static int planar_get(int x, int y)
{
    int m = BDA8(BDA_VMODE);
    if ((unsigned)x >= (unsigned)planar_bpl() * 8 || (unsigned)y >= (unsigned)planar_h(m)) return 0;
    volatile uint8_t *p = VGAMEM + y * planar_bpl() + (x >> 3);
    int v = 0;
    for (int pl = 3; pl >= 0; pl--) { gc(4, pl); v = (v << 1) | ((*p >> (7 - (x & 7))) & 1); }
    gc(4, 0);
    return v;
}

static void put_pixel(int x, int y, int color)
{
    int m = BDA8(BDA_VMODE);
    if (is_planar(m)) { planar_put(x, y, color); return; }
    if (m == 0x62) {
        if ((unsigned)x >= LFB_W || (unsigned)y >= LFB_H) return;
        volatile uint8_t *p = VGAMEM + y * LFB_W + x;
        if (color & 0x80) *p ^= color & 0x7F; else *p = color;
        return;
    }
    if (m == 0x13) {
        if ((unsigned)x < 320 && (unsigned)y < 200) VGAMEM[y * 320 + x] = color;
        return;
    }
    if (m == 4 || m == 5) {
        if ((unsigned)x >= 320 || (unsigned)y >= 200) return;
        volatile uint8_t *p = CGAMEM + (y & 1) * 0x2000 + (y >> 1) * 80 + (x >> 2);
        int sh = (3 - (x & 3)) * 2;
        uint8_t c = (color & 3) << sh;
        if (color & 0x80) *p ^= c;
        else *p = (*p & ~(3 << sh)) | c;
        return;
    }
    if (m == 6) {
        if ((unsigned)x >= 640 || (unsigned)y >= 200) return;
        volatile uint8_t *p = CGAMEM + (y & 1) * 0x2000 + (y >> 1) * 80 + (x >> 3);
        int sh = 7 - (x & 7);
        uint8_t c = (color & 1) << sh;
        if (color & 0x80) *p ^= c;
        else *p = (*p & ~(1 << sh)) | c;
    }
}

static int get_pixel(int x, int y)
{
    int m = BDA8(BDA_VMODE);
    if (is_planar(m)) return planar_get(x, y);
    if (m == 0x13) return ((unsigned)x < 320 && (unsigned)y < 200) ? VGAMEM[y * 320 + x] : 0;
    if (m == 0x62) return ((unsigned)x < LFB_W && (unsigned)y < LFB_H) ? VGAMEM[y * LFB_W + x] : 0;
    if (m == 4 || m == 5) {
        volatile uint8_t *p = CGAMEM + (y & 1) * 0x2000 + (y >> 1) * 80 + (x >> 2);
        return (*p >> ((3 - (x & 3)) * 2)) & 3;
    }
    if (m == 6) {
        volatile uint8_t *p = CGAMEM + (y & 1) * 0x2000 + (y >> 1) * 80 + (x >> 3);
        return (*p >> (7 - (x & 7))) & 1;
    }
    return 0;
}

/* draw a glyph from the 8x8 font (8x16 in mode 62h) in a graphics mode;
   bit 7 of attr = XOR */
static void gfx_char(int row, int col, int ch, int attr)
{
    int m = BDA8(BDA_VMODE);
    int h = gfx_cell(m);
    const uint8_t *g = h == 16 ? font8x16 + (ch & 0xFF) * 16 : h == 14 ? font8x16 + (ch & 0xFF) * 16 + 1 : font8x8 + (ch & 0xFF) * 8;
    int bg = 0;
    for (int y = 0; y < h; y++) {
        uint8_t bits = g[y];
        for (int x = 0; x < 8; x++) {
            int on = bits & (0x80 >> x);
            if (attr & 0x80) { if (on) put_pixel(col * 8 + x, row * h + y, attr); }
            else put_pixel(col * 8 + x, row * h + y, on ? attr : bg);
        }
    }
}

/* ---------------------------------------------------------- text ops */

static volatile uint16_t *cell_ptr(int page, int row, int col)
{
    int cols = BDA16(BDA_VCOLS);
    return text_base() + (page * BDA16(BDA_VPAGESIZE)) / 2 + row * cols + col;
}

void video_scroll(int up, int lines, int attr, int r1, int c1, int r2, int c2)
{
    int m = BDA8(BDA_VMODE);
    int cols = BDA16(BDA_VCOLS);
    int rows = BDA8(BDA_VROWS) + 1;
    if (r2 >= rows) r2 = rows - 1;
    if (c2 >= cols) c2 = cols - 1;
    if (r1 > r2 || c1 > c2) return;
    int h = r2 - r1 + 1;
    if (lines == 0 || lines > h) lines = h;

    if (is_text(m)) {
        int page = BDA8(BDA_VPAGE);
        uint16_t blank = (attr << 8) | ' ';
        if (up) {
            for (int r = r1; r <= r2; r++) {
                volatile uint16_t *d = cell_ptr(page, r, c1);
                if (r + lines <= r2) {
                    volatile uint16_t *s = cell_ptr(page, r + lines, c1);
                    for (int c = 0; c <= c2 - c1; c++) d[c] = s[c];
                } else for (int c = 0; c <= c2 - c1; c++) d[c] = blank;
            }
        } else {
            for (int r = r2; r >= r1; r--) {
                volatile uint16_t *d = cell_ptr(page, r, c1);
                if (r - lines >= r1) {
                    volatile uint16_t *s = cell_ptr(page, r - lines, c1);
                    for (int c = 0; c <= c2 - c1; c++) d[c] = s[c];
                } else for (int c = 0; c <= c2 - c1; c++) d[c] = blank;
            }
        }
        return;
    }
    /* graphics: move character rows (8 pixels high, 16 in mode 62h) */
    int fill = (m == 0x13 || m == 0x62) ? attr : is_planar(m) ? (attr & 15) : (attr & (m == 6 ? 1 : 3));
    int pxw = 8, ch = gfx_cell(m);
    if (m == 0x62) {        /* linear: whole row spans at once */
        for (int step = 0; step < h; step++) {
            int r = up ? r1 + step : r2 - step;
            int src = up ? r + lines : r - lines;
            for (int y = 0; y < ch; y++) {
                volatile uint8_t *d = VGAMEM + (r * ch + y) * LFB_W + c1 * pxw;
                int n = (c2 - c1 + 1) * pxw;
                if (src >= r1 && src <= r2) {
                    volatile uint8_t *sp = VGAMEM + (src * ch + y) * LFB_W + c1 * pxw;
                    for (int x = 0; x < n; x++) d[x] = sp[x];
                } else for (int x = 0; x < n; x++) d[x] = fill;
            }
        }
        return;
    }
    if (is_planar(m)) {     /* a byte moves 8 pixels of all four planes through the latches (write mode 1) */
        int bpl = planar_bpl();
        outb(0x3C4, 2); outb(0x3C5, 0x0F);
        for (int step = 0; step < h; step++) {
            int r = up ? r1 + step : r2 - step;
            int src = up ? r + lines : r - lines;
            for (int y = 0; y < ch; y++) {
                volatile uint8_t *d = VGAMEM + (r * ch + y) * bpl + c1;
                int n = c2 - c1 + 1;
                if (src >= r1 && src <= r2) {
                    volatile uint8_t *sp = VGAMEM + (src * ch + y) * bpl + c1;
                    gc(5, 1);
                    for (int x = 0; x < n; x++) { (void)sp[x]; d[x] = 0; }
                } else {
                    gc(5, 2);
                    for (int x = 0; x < n; x++) d[x] = fill;
                }
            }
        }
        gc(5, 0);
        return;
    }
    for (int step = 0; step < h; step++) {
        int r = up ? r1 + step : r2 - step;
        int src = up ? r + lines : r - lines;
        for (int y = 0; y < ch; y++)
            for (int x = c1 * pxw; x < (c2 + 1) * pxw; x++) {
                int v = (src >= r1 && src <= r2) ? get_pixel(x, src * ch + y) : fill;
                put_pixel(x, r * ch + y, v);
            }
    }
}

void video_goto(int row, int col)
{
    int page = BDA8(BDA_VPAGE);
    BDA16(BDA_CURPOS + page * 2) = (row << 8) | col;
    update_cursor_hw();
}

void video_get_cursor(int *row, int *col)
{
    uint16_t p = BDA16(BDA_CURPOS + BDA8(BDA_VPAGE) * 2);
    *row = p >> 8;
    *col = p & 0xFF;
}

static void write_cell(int page, int row, int col, int ch, int attr, int keep_attr)
{
    int m = BDA8(BDA_VMODE);
    if (is_text(m)) {
        volatile uint16_t *p = cell_ptr(page, row, col);
        if (keep_attr) *p = (*p & 0xFF00) | (ch & 0xFF);
        else *p = (attr << 8) | (ch & 0xFF);
    } else {
        gfx_char(row, col, ch, keep_attr ? ((m == 0x13 || m == 0x62 || is_planar(m)) ? 15 : 3) : attr);
    }
}

static void tty_out(int c, int attr, int use_attr)
{
    int page = BDA8(BDA_VPAGE);
    int cols = BDA16(BDA_VCOLS);
    int rows = BDA8(BDA_VROWS) + 1;
    int row, col;
    video_get_cursor(&row, &col);
    switch (c) {
    case 7:  beep(880, 180); return;
    case 8:  if (col > 0) col--; break;
    case 10: row++; break;
    case 13: col = 0; break;
    default:
        write_cell(page, row, col, c, attr, !use_attr);
        if (++col >= cols) { col = 0; row++; }
        break;
    }
    if (row >= rows) {
        int blank = 0x07;
        if (is_text(BDA8(BDA_VMODE))) blank = (*cell_ptr(page, rows - 1, cols - 1) >> 8) & 0xFF;
        else blank = 0;
        video_scroll(1, 1, blank, 0, 0, rows - 1, cols - 1);
        row = rows - 1;
    }
    video_goto(row, col);
}

void video_putc(int c) { tty_out(c, 0x07, 0); }
void video_putc_attr(int c, int attr) { tty_out(c, attr, 1); }
void video_puts(const char *s) { while (*s) { if (*s == '\n') video_putc('\r'); video_putc(*s++); } }

void video_write_at(int row, int col, const char *s, int attr)
{
    int page = BDA8(BDA_VPAGE);
    for (; *s; s++, col++) write_cell(page, row, col, (uint8_t)*s, attr, attr < 0);
}

void video_fill(int row, int col, int n, int ch, int attr)
{
    int page = BDA8(BDA_VPAGE);
    while (n-- > 0) write_cell(page, row, col++, ch, attr, attr < 0);
}

/* ------------------------------------------------------------ INT 10h */

void int10_handler(struct armregs *f)
{
    int page, row, col;
    switch (AH(f)) {
    case 0x00:
        video_set_mode(AL(f));
        set_al(f, BDA8(BDA_VMODE) <= 7 && BDA8(BDA_VMODE) != 6 ? 0x30 : 0x20);
        break;
    case 0x01:
        video_cursor_shape(CH(f) & 0x3F, CL(f) & 0x1F);
        if (CH(f) & 0x20) crtc(0x0A, 0x20);
        break;
    case 0x02:
        page = BH(f) & 7;
        BDA16(BDA_CURPOS + page * 2) = (DH(f) << 8) | DL(f);
        if (page == BDA8(BDA_VPAGE)) update_cursor_hw();
        break;
    case 0x03:
        page = BH(f) & 7;
        f->r3 = BDA16(BDA_CURPOS + page * 2);
        f->r2 = BDA16(BDA_CURSHAPE);
        break;
    case 0x04:      /* light pen: none */
        set_ah(f, 0);
        break;
    case 0x05:
        if (video_mono()) break;        /* the MDA has one page */
        page = AL(f) & 7;
        if (is_text(BDA8(BDA_VMODE))) {
            BDA8(BDA_VPAGE) = page;
            BDA16(BDA_VPAGESTART) = page * BDA16(BDA_VPAGESIZE);
            uint16_t w = BDA16(BDA_VPAGESTART) / 2;
            crtc(0x0C, w >> 8); crtc(0x0D, w & 0xFF);
            update_cursor_hw();
        }
        break;
    case 0x06:
    case 0x07:
        video_scroll(AH(f) == 6, AL(f), BH(f), CH(f), CL(f), DH(f), DL(f));
        break;
    case 0x08: {
        page = BH(f) & 7;
        uint16_t pos = BDA16(BDA_CURPOS + page * 2);
        if (is_text(BDA8(BDA_VMODE))) set_ax(f, *cell_ptr(page, pos >> 8, pos & 0xFF));
        else set_ax(f, 0);
        break;
    }
    case 0x09:
    case 0x0A: {
        page = BH(f) & 7;
        uint16_t pos = BDA16(BDA_CURPOS + page * 2);
        row = pos >> 8; col = pos & 0xFF;
        int cols = BDA16(BDA_VCOLS);
        int n = f->r2 & 0xFFFF;
        for (int i = 0; i < n; i++) {
            write_cell(page, row, col, AL(f), BL(f), AH(f) == 0x0A && is_text(BDA8(BDA_VMODE)));
            if (++col >= cols) { col = 0; if (++row > BDA8(BDA_VROWS)) break; }
        }
        break;
    }
    case 0x0B:
        if (video_mono()) break;
        if (BH(f) == 0) BDA8(BDA_CGAPAL) = (BDA8(BDA_CGAPAL) & 0xE0) | (BL(f) & 0x1F);
        else BDA8(BDA_CGAPAL) = (BDA8(BDA_CGAPAL) & ~0x20) | ((BL(f) & 1) ? 0x20 : 0);
        outb(0x3D9, BDA8(BDA_CGAPAL));
        break;
    case 0x0C:
        put_pixel(f->r2 & 0xFFFF, f->r3 & 0xFFFF, AL(f));
        break;
    case 0x0D:
        set_al(f, get_pixel(f->r2 & 0xFFFF, f->r3 & 0xFFFF));
        break;
    case 0x0E:
        if (is_text(BDA8(BDA_VMODE))) video_putc(AL(f));
        else tty_out(AL(f), BL(f) ? BL(f) : ((BDA8(BDA_VMODE) == 0x13 || BDA8(BDA_VMODE) == 0x62 || is_planar(BDA8(BDA_VMODE))) ? 15 : 3), 1);
        break;
    case 0x0F:
        set_al(f, BDA8(BDA_VMODE));
        set_ah(f, BDA16(BDA_VCOLS));
        set_bh(f, BDA8(BDA_VPAGE));
        break;
    case 0x10:
        if (video_mono()) {             /* no palette on an MDA; blink/intensity is its mode register */
            if (AL(f) == 0x03) set_blink(BL(f) & 1);
            break;
        }
        switch (AL(f)) {
        case 0x00: attr_write(BL(f) & 0x0F, BH(f)); break;
        case 0x01: attr_write(0x11, BH(f)); break;
        case 0x02: { const uint8_t *p = (const uint8_t *)f->r3; attr_palette(p); attr_write(0x11, p[16]); break; }
        case 0x03: set_blink(BL(f) & 1); break;
        case 0x10:
            outb(0x3C8, BL(f));
            outb(0x3C9, DH(f)); outb(0x3C9, CH(f)); outb(0x3C9, CL(f));
            break;
        case 0x12: {
            const uint8_t *p = (const uint8_t *)f->r3;
            outb(0x3C8, f->r1 & 0xFF);
            for (uint32_t i = 0; i < (f->r2 & 0xFFFF) * 3; i++) outb(0x3C9, p[i]);
            break;
        }
        case 0x15:
            outb(0x3C7, BL(f));
            set_dh(f, inb(0x3C9)); set_ch(f, inb(0x3C9)); set_cl(f, inb(0x3C9));
            break;
        case 0x17: {
            uint8_t *p = (uint8_t *)f->r3;
            outb(0x3C7, f->r1 & 0xFF);
            for (uint32_t i = 0; i < (f->r2 & 0xFFFF) * 3; i++) p[i] = inb(0x3C9);
            break;
        }
        }
        break;
    case 0x11:
        if (video_mono() && AL(f) != 0x30) break;   /* the MDA's font is a ROM on the card */
        switch (AL(f)) {
        case 0x00: case 0x10: {
            const uint8_t *p = (const uint8_t *)f->r6;
            int bpc = BH(f), first = f->r3 & 0xFF, n = f->r2 & 0xFFFF;
            for (int c = 0; c < n && first + c < 256; c++)
                for (int r = 0; r < 32; r++)
                    FONTRAM[(first + c) * 32 + r] = r < bpc ? p[c * bpc + r] : 0;
            break;
        }
        case 0x04: video_load_text_font(); break;
        case 0x14: if (is_text(BDA8(BDA_VMODE))) text_cell(16); break;
        case 0x11: if (is_text(BDA8(BDA_VMODE))) text_cell(14); break;
        case 0x12: if (is_text(BDA8(BDA_VMODE))) text_cell(8); break;
        case 0x01: case 0x02: break;
        case 0x30:
            f->r2 = BDA8(BDA_CHARHEIGHT);
            set_dl(f, BDA8(BDA_VROWS));
            switch (BH(f)) {
            case 0x03: case 0x02: f->r6 = (uint32_t)font8x8; break;
            default: f->r6 = (uint32_t)font8x16; break;
            }
            break;
        }
        break;
    case 0x12:
        if (video_mono()) break;        /* no EGA/VGA: BL stays 10h */
        if (BL(f) == 0x10) { set_bh(f, 0); set_bl(f, 3); f->r2 = 0x0009; }
        else if (BL(f) == 0x30 || BL(f) == 0x31 || BL(f) == 0x32 || BL(f) == 0x33 || BL(f) == 0x34) set_al(f, 0x12);
        break;
    case 0x13: {
        page = BH(f) & 7;
        const uint8_t *s = (const uint8_t *)f->r6;
        int n = f->r2 & 0xFFFF, mode = AL(f);
        int attr = BL(f);
        uint16_t saved = BDA16(BDA_CURPOS + page * 2);
        BDA16(BDA_CURPOS + page * 2) = (DH(f) << 8) | DL(f);
        for (int i = 0; i < n; i++) {
            int ch = *s++;
            if (mode & 2) attr = *s++;
            if (ch == 7 || ch == 8 || ch == 10 || ch == 13) tty_out(ch, attr, 1);
            else tty_out(ch, attr, 1);
        }
        if (!(mode & 1)) { BDA16(BDA_CURPOS + page * 2) = saved; update_cursor_hw(); }
        break;
    }
    case 0x1A:
        if (video_mono()) break;        /* a VGA BIOS function: absent with an MDA/Hercules */
        if (AL(f) == 0) { set_al(f, 0x1A); f->r1 = 0x0008; }
        break;
    case 0x1B:
        if (video_mono()) break;
        if ((f->r1 & 0xFFFF) == 0) {
            static const uint8_t func_table[16] = { 0x7F, 0xFF, 0x0F, 0, 0, 0, 0, 0x07, 0x02, 0x08, 0xFF, 0x0E, 0, 0, 0, 0 };
            uint8_t *b = (uint8_t *)f->r5;
            memset(b, 0, 64);
            *(uint32_t *)b = (uint32_t)func_table;
            b[4] = BDA8(BDA_VMODE);
            b[5] = BDA16(BDA_VCOLS); b[6] = 0;
            b[7] = BDA16(BDA_VPAGESIZE) & 0xFF; b[8] = BDA16(BDA_VPAGESIZE) >> 8;
            for (int i = 0; i < 8; i++) { b[0x0B + i * 2] = BDA16(BDA_CURPOS + i * 2) & 0xFF; b[0x0C + i * 2] = BDA16(BDA_CURPOS + i * 2) >> 8; }
            b[0x1B] = BDA16(BDA_CURSHAPE) & 0xFF; b[0x1C] = BDA16(BDA_CURSHAPE) >> 8;
            b[0x1D] = BDA8(BDA_VPAGE);
            b[0x22] = BDA8(BDA_VROWS) + 1;
            b[0x23] = BDA8(BDA_CHARHEIGHT);
            b[0x25] = 0x08;     /* active display: VGA colour */
            {
                int c256 = BDA8(BDA_VMODE) == 0x13 || BDA8(BDA_VMODE) == 0x62;
                b[0x27] = c256 ? 0 : 16; b[0x28] = c256 ? 1 : 0;
            }
            b[0x29] = 8;        /* pages */
            b[0x2A] = (BDA8(BDA_VMODE) == 0x62 || BDA8(BDA_VMODE) == 0x12) ? 3 : BDA8(BDA_VMODE) == 0x10 ? 1 : 2;  /* 480 / 350 / 400 scan lines */
            set_al(f, 0x1B);
        }
        break;
    case 0x1C:
        set_al(f, 0);   /* save/restore state: not supported */
        break;
    default:
        break;
    }
}
