ATTRIB \AT\*.* > \OUT\AT1.TXT
ATTRIB /S \AT\*.TXT > \OUT\AT2.TXT
ATTRIB \AT\*.* /S > \OUT\AT3.TXT
ATTRIB +R \AT\F1.TXT > \OUT\AT4.TXT
ATTRIB \AT\F1.TXT > \OUT\AT5.TXT
ATTRIB -A \AT\F2.DAT > \OUT\AT6.TXT
ATTRIB \AT\*.* > \OUT\AT7.TXT
ATTRIB -R +A \AT\F1.TXT > \OUT\AT8.TXT
ATTRIB +A \AT\F2.DAT
ATTRIB +R +A \AT\SUB\*.* > \OUT\AT9.TXT
ATTRIB /S \AT\*.* > \OUT\AT10.TXT
ATTRIB -R \AT\SUB\*.*
ATTRIB /S \AT\*.* > \OUT\AT11.TXT
CD \AT
ATTRIB *.* > \OUT\AT12.TXT
ATTRIB . > \OUT\AT13.TXT
ATTRIB F1.TXT > \OUT\AT14.TXT
CD SUB
ATTRIB .. > \OUT\AT15.TXT
ATTRIB DEEP > \OUT\AT16.TXT
ATTRIB DEEP\*.* > \OUT\AT17.TXT
ATTRIB C:*.* > \OUT\AT18.TXT
CD \
ATTRIB \AT\F1.TXT FILESIZE > \OUT\AT19.TXT
ATTRIB \AT\F1.TXT DATE > \OUT\AT20.TXT
ATTRIB \AT\F1.TXT TIME > \OUT\AT21.TXT
ATTRIB \AT\F1.TXT CODEPAGE > \OUT\AT22.TXT
ATTRIB \AT\F1.TXT * > \OUT\AT23.TXT
ATTRIB \AT\F1.TXT FOO > \OUT\AT24.TXT
ATTRIB \AT\*.* FILESIZE > \OUT\AT25.TXT
ATTRIB \AT\F1.TXT > NUL
ECHO ok >> \OUT\EL.TXT
IF ERRORLEVEL 1 ECHO ATOK 1 >> \OUT\EL.TXT
IF ERRORLEVEL 2 ECHO ATOK 2 >> \OUT\EL.TXT
IF ERRORLEVEL 10 ECHO ATOK 10 >> \OUT\EL.TXT
ATTRIB \NOFILE.TXT > NUL
IF ERRORLEVEL 1 ECHO ATNF 1 >> \OUT\EL.TXT
IF ERRORLEVEL 2 ECHO ATNF 2 >> \OUT\EL.TXT
ATTRIB +X \AT\F1.TXT > NUL
IF ERRORLEVEL 1 ECHO ATX 1 >> \OUT\EL.TXT
IF ERRORLEVEL 2 ECHO ATX 2 >> \OUT\EL.TXT
CLS
ATTRIB +X \AT\F1.TXT
ATTRIB \NOFILE.TXT
ATTRIB \NODIR\X.TXT
ATTRIB Q:\X.TXT
ATTRIB +R +R \AT\F1.TXT
ATTRIB +R -R \AT\F1.TXT
ATTRIB /X \AT\F1.TXT
ATTRIB \AT\F1.TXT \AT\F2.DAT
ATTRIB
ATTRIB /S /S \AT\*.*
ATTRIB \AT\SUB
ATTRIB \AT\F1.TXT=
ATTRIB +A
ATTRIB \AT\F1.TXT CODEPAGE=437
ATTRIB \AT\F1.TXT +R
ATTRIB "\AT\F1.TXT"
ATTRIB \AT\F1.TXT,\AT\F2.DAT
ATTRIB +r \AT\F1.TXT
ATTRIB \AT\F1.TXT
ATTRIB -r \at\f1.txt
SCRDUMP C:\OUT\ERRORS.SCR
