// The inspector's ELBOW view: x86 code being translated to ARM, live.
//
// While ELBOW (apps/x86) runs an x86 program with its translator, the ARM CPU
// spends its time in blocks of ARM code ELBOW generated from the program's x86
// code. This section samples the ARM PC ~10 times a second, finds the block it
// is in (web/js/elbow-probe.js, through the descriptor ELBOW announces on
// ports FCh-FFh, ARCH.md 4.7) and shows that block's x86 instructions next to
// the ARM code made from them. The block shown is the one sampled most over
// the last second or two, so a busy loop stays put instead of flickering; the
// ARM lines the PC was seen on glow. The bar underneath says where the time
// goes: translated code, ELBOW's helpers (string ops, stores that hit code...),
// its x86 interpreter, or DOS/BIOS/IRQs.
//
// Costs nothing while closed (or the inspector is closed, or the tab hidden):
// no hooks; ELBOW does no extra work either way.

import { disasmArm } from '../emu/disasm.js';
import { readElbow, probeElbow, blockDetail, x86lines, hex4 } from './elbow-probe.js';
import { $, hex, el, prefs } from './util.js';

const SAMPLE_MS = 100;
const RENDER_EVERY = 3;                 // samples per redraw (~3 Hz)
const DECAY = 0.93;                     // per sample: a block's score halves in ~1 s
const KINDS = [
  ['block', 'TRANSLATED', 'x'], ['helper', 'HELPERS', 'h'], ['stub', 'EXITS', 'h'], ['interp', 'INTERPRETER', 'i'], ['native', 'DOS · BIOS · IRQ', 'n'],
];
const STATUS = {
  none: 'ELBOW is not running',
  block: 'running ARM code translated from x86',
  helper: 'in an ELBOW helper called by translated code',
  stub: 'leaving a block (exit stub)',
  interp: 'x86 interpreter: this code is not translated (yet)',
  native: 'ELBOW has handed over to ARM-DOS / the BIOS / an IRQ',
};
const esc = (s) => String(s).replace(/[&<>"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));

export class ElbowPanel {
  /** ctl: { machine() -> Machine|null, running() -> bool } */
  constructor(ctl) {
    this.ctl = ctl;
    this.scores = new Map();            // block code address -> recent sample score
    this.hist = [];                     // kinds of the last ~2 s of samples
    this.shown = null;                  // { key, detail, hits: Map(index -> count) }
    this.n = 0; this.lastKind = 'none'; this.lastProbe = null; this.idleDesc = -1;
    this.build();
    this.setOpen(prefs.get('elbow', false));
    this.timer = setInterval(() => this.tick(), SAMPLE_MS);
  }

  build() {
    this.btn = el('button', { class: 'hwkey small', id: 'ebToggle', 'aria-expanded': 'false', 'aria-controls': 'elbowView', text: 'OPEN' });
    this.stateEl = el('span', { class: 'eb-state', id: 'ebState', text: '' });
    const cap = el('div', { class: 'section-cap eb-cap' }, el('span', { text: 'ELBOW · X86 → ARM' }), this.stateEl, this.btn);
    this.statusEl = el('div', { class: 'eb-status', id: 'ebStatus' });
    this.barEl = el('div', { class: 'eb-bar', id: 'ebBar', 'aria-label': 'Where the ARM CPU spent the last two seconds' });
    this.headEl = el('div', { class: 'eb-head', id: 'ebHead' });
    this.x86El = el('div', { class: 'eb-list eb-x86', id: 'ebX86', 'aria-label': 'x86 instructions of the block' });
    this.armEl = el('div', { class: 'eb-list eb-arm', id: 'ebArm', 'aria-label': 'ARM code ELBOW generated for it' });
    this.armCap = el('span', { text: 'ARM · GENERATED BY ELBOW' });
    this.footEl = el('div', { class: 'eb-foot', id: 'ebFoot' });
    this.box = el('div', { class: 'win eb', id: 'elbowView', hidden: true },
      this.statusEl, this.barEl, this.headEl,
      el('div', { class: 'eb-cols' },
        el('div', { class: 'eb-col' }, el('div', { class: 'eb-vcap' }, el('span', { text: 'X86 · THE PROGRAM' })), this.x86El),
        el('div', { class: 'eb-col' }, el('div', { class: 'eb-vcap' }, this.armCap), this.armEl)),
      this.footEl);
    const before = $('intlog')?.previousElementSibling;          // the INTERRUPTS caption
    if (before && before.classList.contains('section-cap')) before.before(cap, this.box);
    else $('inspBody')?.append(cap, this.box);
    this.btn.onclick = () => this.setOpen(!this.open);
  }

  setOpen(on) {
    this.open = on;
    this.box.hidden = !on;
    this.btn.textContent = on ? 'CLOSE' : 'OPEN';
    this.btn.setAttribute('aria-expanded', String(on));
    prefs.set('elbow', on);
    this.scores.clear(); this.hist = []; this.shown = null; this.n = 0; this.lastKind = ''; this.idleDesc = -1;
    if (on) this.tick(true);
  }

  visible() { return !document.hidden && !$('inspector')?.classList.contains('closed'); }

  tick(force) {
    if (!this.visible()) return;
    const m = this.ctl.machine();
    if (!this.open) {                    // closed: only the caption says whether there is anything to see
      const d = m ? m.elbowDesc >>> 0 : 0;
      if (d !== this.idleDesc) { this.idleDesc = d; this.stateEl.textContent = d ? 'X86 RUNNING' : ''; this.stateEl.classList.toggle('lit', !!d); }
      return;
    }
    const running = !!m && this.ctl.running();
    if (running || force || !this.lastProbe) this.sample(m);
    if (force || ++this.n % RENDER_EVERY === 0) this.render(m);
  }

  sample(m) {
    let E = null, p = { kind: 'none' };
    try { E = readElbow(m); p = probeElbow(m, E); } catch { p = { kind: 'none' }; }
    if ((p.kind === 'none') !== (this.lastProbe?.kind === 'none')) this.hist = [];     // ELBOW started / ended
    this.lastProbe = p;
    this.hist.push(p.kind); if (this.hist.length > 20) this.hist.shift();
    for (const [k, v] of this.scores) { const n = v * DECAY; if (n < 0.05) this.scores.delete(k); else this.scores.set(k, n); }
    if (!E) { this.E = null; return; }
    if (this.E && this.E.cache !== E.cache) { this.scores.clear(); this.shown = null; }     // another ELBOW run
    this.E = E;
    const b = p.block;
    if (b) {
      const key = b.code;
      this.scores.set(key, (this.scores.get(key) || 0) + 1);
      if (this.shown && this.shown.key === key) {
        const idx = ((p.kind === 'block' ? p.pc : p.from) - b.code) >>> 2;
        this.shown.hits.set(idx, (this.shown.hits.get(idx) || 0) + 1);
        this.shown.last = idx; this.shown.lastKind = p.kind;
      }
    }
  }

  // the block to show: the best recent score, with some hysteresis
  pick() {
    const E = this.E;
    let best = null, bs = 0;
    for (const [k, v] of this.scores) if (v > bs) { best = k; bs = v; }
    const cur = this.shown && this.scores.get(this.shown.key);
    if (this.shown && !this.stillThere(this.shown)) { this.shown = null; }
    if (best === null) return;
    if (this.shown && (best === this.shown.key || (cur || 0) * 1.6 >= bs)) return;
    const b = E.blockByCode(best);
    if (!b) { this.scores.delete(best); return; }
    const p = this.lastProbe;
    const detail = blockDetail(E, b, disasmArm);
    const hits = new Map();
    if (p && p.block && p.block.code === best) { const i = ((p.kind === 'block' ? p.pc : p.from) - b.code) >>> 2; hits.set(i, 1); }
    this.shown = { key: best, lin: b.lin, cs: b.cs, detail, hits, last: hits.size ? [...hits.keys()][0] : -1, lastKind: p?.kind, built: false };
  }
  // after a cache refill (or an invalidation) the ARM code at that address is something else
  stillThere(s) {
    const b = this.E && this.E.blockByCode(s.key);
    return !!b && b.lin === s.lin && b.cs === s.cs;
  }

  render(m) {
    const E = this.E, p = this.lastProbe || { kind: 'none' };
    if (!m || !E) {
      this.stateEl.textContent = m ? 'IDLE' : 'NO POWER'; this.stateEl.classList.remove('lit');
      this.statusEl.innerHTML = `<span class="eb-lamp"></span><span>${m ? 'ELBOW is not running.' : 'The machine is off.'}</span>`;
      this.barEl.innerHTML = ''; this.headEl.textContent = '';
      if (this.lastKind !== 'none') {
        this.x86El.innerHTML = `<div class="eb-note">Run an x86 program - <b>X86GAMES</b>, <b>C:\\ELBOW\\DEMO</b>, Second Reality in C:\\ELBOW\\DEMOS\\SECOND - and watch its x86 code being turned into ARM code here.</div>`;
        this.armEl.innerHTML = '<div class="eb-note">ELBOW translates hot x86 code into ARM blocks in a code cache; the ARM CPU then runs those at full speed.</div>';
        this.footEl.textContent = ''; this.shown = null; this.lastKind = 'none';
      }
      return;
    }
    this.lastKind = p.kind;
    this.stateEl.textContent = E.jit ? 'TRANSLATING' : 'INTERPRETER ONLY'; this.stateEl.classList.add('lit');
    // where the time went
    const cnt = {}; for (const k of this.hist) cnt[k] = (cnt[k] || 0) + 1;
    const tot = this.hist.length || 1;
    this.barEl.innerHTML = '<div class="eb-bar-track">' + KINDS.map(([k, , c]) => { const n = cnt[k] || 0; return n ? `<i class="${c}" style="flex:${n}"></i>` : ''; }).join('') + '</div>'
      + '<div class="eb-legend">' + KINDS.filter(([k]) => k !== 'stub').map(([k, name, c]) => { const n = (cnt[k] || 0) + (k === 'helper' ? cnt.stub || 0 : 0); return `<span class="${c}${n ? '' : ' off'}">${name} ${Math.round(n * 100 / tot)}%</span>`; }).join('') + '</div>';
    this.pick();
    const s = this.shown;
    let status = STATUS[p.kind] || '';
    if (p.kind === 'interp') status += ` · <b>${hex4(p.cs)}:${hex4(p.ip)}</b>`;
    if (s && p.kind !== 'block' && !(p.kind === 'helper' && p.block && p.block.code === s.key)) status += ' <span class="eb-dim">· showing the busiest recent block</span>';
    this.statusEl.innerHTML = `<span class="eb-lamp ${p.kind === 'block' ? 'x' : p.kind === 'interp' ? 'i' : p.kind === 'native' ? 'n' : 'h'}"></span><span>${status}</span>`;
    this.footEl.textContent = E.jit
      ? `${E.nblk.toLocaleString('en-US')} blocks in the cache (${Math.round((E.cp - E.cache) / 1024)} KB of ARM code) · ${E.translated.toLocaleString('en-US')} translated since start${E.flushes ? ` · cache refilled ${E.flushes}×` : ''}`
      : 'ELBOW /NOJIT: every x86 instruction goes through the interpreter';
    if (s) this.renderBlock(s);
    else if (p.kind === 'interp') this.renderInterp(E, p);
    else if (!E.jit || !this.scores.size) this.renderWaiting();
  }

  renderWaiting() {
    if (this.mode === 'wait') return;
    this.mode = 'wait';
    this.headEl.textContent = '';
    this.x86El.innerHTML = '<div class="eb-note">Waiting for x86 code to get hot…</div>';
    this.armEl.innerHTML = '';
  }

  renderInterp(E, p) {
    this.mode = 'interp';
    this.headEl.innerHTML = `<b>${hex4(p.cs)}:${hex4(p.ip)}</b> · interpreted`;
    const lines = x86lines(E, p.cs, p.ip, { count: 8 });
    this.x86El.innerHTML = lines.map((l, k) => this.x86Line(l, k === 0)).join('');
    this.armCap.textContent = 'ARM';
    this.armEl.innerHTML = `<div class="eb-note">${E.jit ? 'Not translated: code runs through the interpreter until it is seen twice (then it becomes a block), and for instructions the translator leaves to it (INT, IRET, POPF...).' : 'The translator is off (ELBOW /NOJIT): the interpreter (apps/x86/cpu.c) decodes and executes every x86 instruction in C.'}</div>`;
  }

  x86Line(l, cur) {
    const tgt = l.target !== undefined ? ' eb-br' : '';
    return `<div class="ln${cur ? ' cur' : ''}${l.follow ? ' follow' : ''}${tgt}" title="${hex4(l.cs)}:${hex4(l.ip)}  ${l.bytes}"><span class="ad">${hex4(l.ip)}</span><span class="mn">${esc(l.mnem)}</span><span class="tx">${esc(l.ops)}</span></div>`;
  }

  renderBlock(s) {
    const d = s.detail;
    if (!s.built || this.mode !== 'block') {
      this.mode = 'block'; s.built = true;
      const ratio = d.nx86 ? (d.narm / d.nx86).toFixed(1) : '-';
      this.headEl.innerHTML = `BLOCK <b>${hex4(d.cs)}:${hex4(d.ip)}</b> · ${d.nx86} x86 → ${d.narm} ARM instructions <span class="eb-dim">(${ratio} each) · @${hex(d.code, 6)}${d.dead ? ' · invalidated' : ''}</span>`;
      this.x86El.innerHTML = d.x86.map((l) => this.x86Line(l, false)).join('');
      this.armCap.textContent = 'ARM · GENERATED BY ELBOW';
      this.armEl.innerHTML = d.arm.map((l, i) => {
        const [mn, ...rest] = l.text.split(' ');
        return `<div class="ln${l.lit ? ' lit' : ''}" data-i="${i}" title="${hex(l.addr, 6)}  ${hex(l.word)}${l.note ? '  ' + esc(l.note) : ''}"><span class="ad">${hex(l.addr & 0xFFFF, 4)}</span><span class="mn">${esc(mn)}</span><span class="tx">${esc(rest.join(' '))}${l.note ? ` <em>${esc(l.note)}</em>` : ''}</span></div>`;
      }).join('');
      this.armRows = [...this.armEl.children]; this.curRow = null;
      this.armEl.scrollTop = 0;
      this.hitShown = new Map();
    }
    // the lines the PC was sampled on glow; the latest has the marker
    let max = 1; for (const v of s.hits.values()) max = Math.max(max, v);
    for (const [i, v] of s.hits) {
      const r = this.armRows[i]; if (!r) continue;
      const lvl = Math.min(4, 1 + Math.floor((v / max) * 3.999));
      if (this.hitShown.get(i) !== lvl) { r.classList.remove('h1', 'h2', 'h3', 'h4'); r.classList.add('h' + lvl); this.hitShown.set(i, lvl); }
    }
    if (this.curRow) this.curRow.classList.remove('cur', 'call');
    const r = this.armRows[s.last];
    if (r) {
      r.classList.add('cur'); if (s.lastKind === 'helper') r.classList.add('call');
      this.curRow = r;
      const box = this.armEl, top = r.offsetTop;              // (.eb-list is position: relative)
      if (top < box.scrollTop || top > box.scrollTop + box.clientHeight - r.offsetHeight) box.scrollTop = Math.max(0, top - box.clientHeight / 3);
    }
  }
}
