SUBST > \OUT\S0.TXT
SUBST E: \SUB > \OUT\S1.TXT
SUBST > \OUT\S2.TXT
DEL E:*.TXT
SUBST E: /D > \OUT\S3.TXT
SUBST > \OUT\S4.TXT
SUBST D: C:\SUB
SUBST > \OUT\S5.TXT
SUBST D: /D
SUBST E: \SUB
IF ERRORLEVEL 1 ECHO SE1 >> \OUT\EL.TXT
SUBST E: \NODIR
IF ERRORLEVEL 1 ECHO SE2 >> \OUT\EL.TXT
SUBST E: /D
CLS
SUBST X: \WORK
SUBST E: \NODIR
SUBST E:
SUBST \WORK
SUBST E: /D
SUBST C: \WORK
SUBST E: C:\WORK\A.TXT
SUBST E: \WORK /D
SUBST E: \WORK X
SUBST /X
SUBST E: \WORK
SUBST E: \SUB
SUBST E: /D
SUBST E: /D /D
SUBST E: \
SUBST C: /D
SCRDUMP C:\OUT\ERRORS.SCR
