// The telephone network for the ARM-PC modems (docs/MODEM.md): a PhoneExchange shared by
// every machine on a page (or in a node test), plus a message-port bridge so a modem in a
// Web Worker can sit on the same exchange as the page.
//
// Vocabulary
//   endpoint   something with a phone number: a Modem (dev/modem.mjs), the page's Host Link,
//              a PortEndpoint standing in for a worker's modem. It implements
//                  incoming(leg) -> true (it will ring) | 'busy'
//   leg        one end of a call. Its owner (whoever holds it) sets leg.owner = {
//                  onRinging()      caller: the far end is being rung (play ringback)
//                  onBusy()         caller: the number is busy
//                  onAnswer(rate)   caller: the far end went off hook and will train at rate
//                  onData(bytes)    bytes from the far end (Uint8Array / number[])
//                  onHangup(why)    the far end hung up ('hangup' | 'cancel')
//                  backlog()        optional: bytes received but not yet delivered to the DTE
//              } and calls leg.send(bytes), leg.answer(maxRate) (callee), leg.hangup().
//
// Nothing here knows about time: each endpoint runs its own clock (a Machine's emulated
// time, the page's wall clock) and paces its side itself. Ring cadence is generated by the
// ringing endpoint, ringback by the calling one. A number nobody registered rings forever
// (the caller's modem gives up with NO ANSWER after S7 seconds).

/** "555-1989", "1-800-555-1989", "(555) 1989" -> "5551989" (the last seven digits). */
export function normalizeNumber(s) {
  const d = String(s).replace(/[^0-9]/g, '');
  if (d.startsWith('011')) return d;              // international: kept whole (011 7 095 ...)
  return d.length > 7 ? d.slice(-7) : d;
}
export const isInternational = (n) => normalizeNumber(n).startsWith('011');
export function formatNumber(s) {
  const d = normalizeNumber(s);
  if (d.startsWith('011')) return d.length === 14 ? `011-${d[3]}-${d.slice(4, 7)}-${d.slice(7, 10)}-${d.slice(10)}` : d;
  return d.length === 7 ? `${d.slice(0, 3)}-${d.slice(3)}` : d;
}

/**
 * The two directions of a call at a nominal rate. V.90 (56000) is asymmetric: the answering
 * side is the "digital" (server) end, 53,333 bps down to the caller, 31,200 bps up.
 */
export function lineRates(nominal) {
  if (nominal >= 56000) return { down: 53333, up: 31200 };
  return { down: nominal, up: nominal };
}

export class Leg {
  constructor(call, role) { this.call = call; this.role = role; this.owner = null; this.open = true; this.peer = null; }
  get connected() { return this.call.answered && this.open && this.peer.open; }
  get rate() { return this.call.rate; }
  /** bits/s this end receives at / transmits at. */
  get rxRate() { return this.role === 'caller' ? this.call.down : this.call.up; }
  get txRate() { return this.role === 'caller' ? this.call.up : this.call.down; }
  /** Bytes to the far end. Dropped unless the call is answered and both ends are up. */
  send(bytes) {
    if (!this.connected || !bytes.length) return;
    this.call.bytes[this.role] += bytes.length;
    this.peer.owner?.onData?.(bytes);
  }
  /**
   * Callee picks up by voice (a person, a PBX, a fax machine): no answer tone and no carrier
   * yet. The caller's modem stops the ringback and keeps listening (its speaker plays what the
   * line sends with lineSound) until a later answer() or a hang-up.
   */
  voice() {
    const c = this.call;
    if (this.role !== 'callee' || c.answered || c.voice || !this.open || !this.peer.open) return;
    c.voice = true;
    this.peer.owner?.onVoice?.();
  }
  /** Audio on the line for the far end's modem speaker: { sound: 'hold' | 'fax', ms }. */
  lineSound(ev) { if (this.open && this.peer.open) this.peer.owner?.onLineSound?.(ev); }
  /** Callee picks up; maxRate = the fastest it can train. Returns the agreed rate. */
  answer(maxRate = 14400) {
    const c = this.call;
    if (this.role !== 'callee' || c.answered || !this.open || !this.peer.open) return 0;
    c.answered = true;
    if (!c.exchange.lineRate) c.rate = Math.min(c.rate, maxRate);
    Object.assign(c, lineRates(c.rate));
    if (c.exchange.lineRate) c.down = c.up = c.rate;
    c.exchange.emit({ type: 'answer', number: c.number, rate: c.rate });
    this.peer.owner?.onAnswer?.(c.rate);
    return c.rate;
  }
  hangup() {
    if (!this.open) return;
    this.open = false;
    const c = this.call;
    c.exchange.emit({ type: 'hangup', number: c.number, by: this.role });
    if (this.peer.open) this.peer.owner?.onHangup?.(c.answered ? 'hangup' : 'cancel');
  }
  /** How many bytes the far end has received but not yet handed to its computer. */
  remoteBacklog() { return this.peer.owner?.backlog?.() ?? 0; }
}

export class Call {
  constructor(exchange, number, rate) {
    this.exchange = exchange; this.number = number; this.rate = rate; this.down = rate; this.up = rate;
    this.answered = false;
    this.bytes = { caller: 0, callee: 0 };
    this.caller = new Leg(this, 'caller');
    this.callee = new Leg(this, 'callee');
    this.caller.peer = this.callee; this.callee.peer = this.caller;
  }
}

export class PhoneExchange {
  /** lineRate: force every call to train at this rate (tests: 115200 = 11,520 chars/s). */
  constructor({ lineRate = 0 } = {}) {
    this.lineRate = lineRate;
    this.lines = new Map();       // number -> endpoint
    this.busyNumbers = new Set(['8675309']);   // Jenny's line is always engaged
    this.listeners = new Set();
    this.calls = 0;
  }
  register(number, endpoint) { this.lines.set(normalizeNumber(number), endpoint); return this; }
  unregister(number, endpoint) {
    const n = normalizeNumber(number);
    if (!endpoint || this.lines.get(n) === endpoint) this.lines.delete(n);
  }
  lookup(number) { return this.lines.get(normalizeNumber(number)) || null; }
  on(fn) { this.listeners.add(fn); return () => this.listeners.delete(fn); }
  emit(ev) { for (const f of this.listeners) { try { f(ev); } catch (e) { console.error(e); } } }

  /**
   * Place a call. owner gets the caller-side callbacks (see the top of this file); the
   * returned leg is the caller's. rate = the line rate the caller wants to train at.
   * The outcome arrives through owner.onRinging / onBusy / onAnswer, synchronously or later.
   */
  dial(number, owner, { rate = 2400 } = {}) {
    const n = normalizeNumber(number);
    const call = new Call(this, n, this.lineRate || rate);
    call.caller.owner = owner;
    this.calls++;
    this.emit({ type: 'dial', number: n });
    const ep = this.lines.get(n);
    let r = this.busyNumbers.has(n) ? 'busy' : true;
    if (r === true && ep) {
      try { r = ep.incoming(call.callee); } catch (e) { console.error(e); r = 'busy'; }
    }
    if (r === 'busy') { call.callee.open = false; owner.onBusy?.(); }
    else owner.onRinging?.({ international: n.startsWith('011') });
    return call.caller;
  }
}

// ------------------------------------------------------------------------------------------
// Bridging an exchange across a message port (page <-> Web Worker).
//
// Page side:   exchange.register('555-1989', new PortEndpoint(msg => worker.postMessage(msg)))
//              worker.onmessage = e => endpoint.handle(e.data)   (for messages with .phone)
// Worker side: const ex = new PortExchange(msg => postMessage(msg));
//              new Machine({ phone: ex, phoneNumber: '555-1989' })  // registers the modem
//              onmessage = e => ex.handle(e.data)
// Messages: { phone: 'incoming'|'answer'|'data'|'hangup'|'consumed'|'onAnswer'|..., id, ... }.
// Only incoming calls cross the bridge (the BBS never dials out); a dial from the worker
// side gets NO DIALTONE-free silence: it rings forever.

export class PortEndpoint {
  constructor(post) { this.post = post; this.legs = new Map(); this.nextId = 1; this.onIncoming = null; }
  incoming(leg) {
    const id = this.nextId++;
    const st = { leg, pending: 0 };
    this.legs.set(id, st);
    leg.owner = {
      onData: (bytes) => { st.pending += bytes.length; this.post({ phone: 'data', id, bytes: Array.from(bytes) }); },
      onHangup: (why) => { this.post({ phone: 'hangup', id, why }); this.legs.delete(id); },
      backlog: () => st.pending,
    };
    this.onIncoming?.(leg);
    this.post({ phone: 'incoming', id, rate: leg.call.rate, number: leg.call.number });
    return true;
  }
  handle(msg) {
    const st = this.legs.get(msg.id);
    if (!st) return;
    switch (msg.phone) {
      case 'answer': st.leg.answer(msg.maxRate); break;
      case 'data': st.leg.send(msg.bytes); break;
      case 'consumed': st.pending = Math.max(0, st.pending - msg.n); break;
      case 'hangup': st.leg.hangup(); this.legs.delete(msg.id); break;
      case 'busy': st.leg.hangup(); this.legs.delete(msg.id); break;
    }
  }
}

class RemoteLeg {
  constructor(px, id, rate, number) {
    this.px = px; this.id = id; this.role = 'callee'; this.owner = null; this.open = true; this.answered = false;
    this.call = { rate, number, answered: false, down: rate, up: rate };
    this.delivered = 0;
  }
  get connected() { return this.answered && this.open; }
  get rate() { return this.call.rate; }
  get rxRate() { return this.call.up; }
  get txRate() { return this.call.down; }
  send(bytes) { if (this.connected && bytes.length) this.px.queue(this.id, bytes); }
  answer(maxRate = 14400) {
    if (this.answered || !this.open) return 0;
    this.answered = this.call.answered = true;
    this.call.rate = Math.min(this.call.rate, maxRate);
    if (!this.forced) Object.assign(this.call, lineRates(this.call.rate));
    this.px.post({ phone: 'answer', id: this.id, maxRate });
    return this.call.rate;
  }
  hangup() { if (!this.open) return; this.open = false; this.px.flush(); this.px.post({ phone: 'hangup', id: this.id }); this.px.legs.delete(this.id); }
  remoteBacklog() { return 0; }
  /** The owner reports bytes it handed to its computer (flow control for the page side). */
  consumed(n) { this.delivered += n; this.px.consumed(this.id, n); }
}

export class PortExchange {
  constructor(post) { this.post = post; this.lines = new Map(); this.legs = new Map(); this.out = new Map(); this.cons = new Map(); this.timer = 0; }
  register(number, endpoint) { this.lines.set(normalizeNumber(number), endpoint); return this; }
  unregister(number) { this.lines.delete(normalizeNumber(number)); }
  lookup(number) { return this.lines.get(normalizeNumber(number)) || null; }
  on() { return () => {}; }
  emit() {}
  dial(number, owner) { return { owner, open: true, connected: false, send() {}, answer() { return 0; }, hangup() {}, remoteBacklog() { return 0; } }; }
  queue(id, bytes) {
    let q = this.out.get(id); if (!q) this.out.set(id, q = []);
    for (const b of bytes) q.push(b);
    this.arm();
  }
  consumed(id, n) { this.cons.set(id, (this.cons.get(id) || 0) + n); this.arm(); }
  arm() { if (!this.timer) this.timer = setTimeout(() => this.flush(), 15); }
  flush() {
    clearTimeout(this.timer); this.timer = 0;
    for (const [id, q] of this.out) if (q.length) this.post({ phone: 'data', id, bytes: q.splice(0) });
    for (const [id, n] of this.cons) if (n) this.post({ phone: 'consumed', id, n });
    this.cons.clear();
  }
  handle(msg) {
    if (!msg || !msg.phone) return false;
    if (msg.phone === 'incoming') {
      const ep = this.lines.values().next().value;
      const leg = new RemoteLeg(this, msg.id, msg.rate, msg.number);
      this.legs.set(msg.id, leg);
      const r = ep ? ep.incoming(leg) : 'busy';
      if (r === 'busy') { this.legs.delete(msg.id); this.post({ phone: 'busy', id: msg.id }); }
      return true;
    }
    const leg = this.legs.get(msg.id);
    if (!leg) return true;
    if (msg.phone === 'data') leg.owner?.onData?.(msg.bytes);
    else if (msg.phone === 'hangup') { leg.open = false; this.legs.delete(msg.id); leg.owner?.onHangup?.(leg.answered ? 'hangup' : 'cancel'); }
    return true;
  }
}
