#!/usr/bin/env node
// apps/hexen2/tests/hostlink.mjs - the Host Link way in, end to end:
// GETPAK.BAT -> TERM /S:GETPAK.SCR dials 555-0100 (emu/hostlink.mjs, the web
// page's JS Host Link), presses D, the "browser" offers pak0.pak, TERM
// receives it by ZMODEM into C:\GAMES\HEXEN2\DATA1, hangs up, and INSTALL
// (H2CHECK) checks it; then the file is compared byte for byte.
//
//   node apps/hexen2/tests/hostlink.mjs [--pak FILE] [--bytes N] [--rate BPS | --real] [--abort-at N]
//
// The visitor's modem tops out at 14,400 bps (27.7 MB = 5 1/2 hours); the
// test runs the line and the UART faster (PhoneExchange lineRate +
// com2.baudOverride, docs/MODEM.md) - the protocol, TERM's script and the
// files are the same; --real runs the visitor's line as GETPAK.SCR sets it
// up (AT&B14400, UART at 19200), in emulated time. --bytes N sends only the first N bytes of the pak
// (as a file named pak0.pak: H2CHECK must then refuse it); --abort-at N
// drops the line after N bytes and runs GETPAK again (ZMODEM crash recovery).
// Without the demo pak, a generated file of --bytes (default 2 MB) is sent.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { boot } from '../../../emu/testkit.mjs';
import { build as buildImage, FatReader } from '../../../disk/mkimage.mjs';
import { PhoneExchange } from '../../../emu/phone.mjs';
import { HostLink } from '../../../emu/hostlink.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const B = (p) => path.join(ROOT, 'build', p);
const argv = process.argv.slice(2);
const opt = (name, def) => { const i = argv.indexOf(name); return i >= 0 ? argv[i + 1] : def; };
const OUT = B('hexen2-test');
const PAK = opt('--pak', process.env.HEXEN2_PAK || '');
const REAL = argv.includes('--real');      // the visitor's own line: TERM's AT&B14400, 19200 bps UART
const RATE = REAL ? 14400 : +opt('--rate', 921600);
const ABORT_AT = +opt('--abort-at', 0);
fs.mkdirSync(OUT, { recursive: true });

let data, real = false;
try { data = fs.readFileSync(PAK); real = data.length === 27750257; } catch { data = null; }
if (opt('--bytes')) data = data ? data.subarray(0, +opt('--bytes')) : null;
if (!data) {
  const n = +opt('--bytes', 2 * 1024 * 1024);
  data = Buffer.alloc(n);
  for (let i = 0; i < n; i++) data[i] = (i * 7 + (i >> 8) * 13 + (i >> 16)) & 0xFF;
  console.log(`(no demo pak: sending ${n} generated bytes as pak0.pak)`);
}
const whole = real && data.length === 27750257;

let failures = 0;
const check = (ok, what) => { console.log(`${ok ? 'ok  ' : 'FAIL'} ${what}`); if (!ok) failures++; return ok; };

// ---- C: with TERM and C:\GAMES\HEXEN2 (no pak)
const frag = JSON.parse(fs.readFileSync(path.join(ROOT, 'apps/hexen2/hd.json'), 'utf8'));
const tmp = fs.mkdtempSync(path.join(OUT, 'hl-'));
const put = (name, text) => { const p = path.join(tmp, name); fs.writeFileSync(p, text.replace(/\r?\n/g, '\r\n')); return p; };
const files = [
  { src: 'build/IO.SYS', attr: 'HSR', first: 1 }, { src: 'build/ARMDOS.SYS', attr: 'HSR', first: 2 },
  { src: 'build/COMMAND.COM' }, { src: 'build/HIMEM.SYS', dst: 'DOS\\' }, { src: 'build/MORE.COM', dst: 'DOS\\' },
  { src: 'build/TERM.EXE', dst: 'TERM\\TERM.EXE' }, { src: 'apps/term/data/TERM.DIR', dst: 'TERM\\TERM.DIR' },
  ...frag.files,
  { src: put('CONFIG.SYS', 'DEVICE=C:\\DOS\\HIMEM.SYS\nFILES=20\n'), dst: 'CONFIG.SYS' },
  { src: put('AUTOEXEC.BAT', '@ECHO OFF\nPATH C:\\DOS\nPROMPT $P$G\n'), dst: 'AUTOEXEC.BAT' },
];
const { img } = buildImage({ format: 'hd', sizeMB: 64, heads: 16, sectorsPerTrack: 63, label: 'HOSTLINK',
  date: '1997-11-07 12:00:00', boot: { src: 'build/bootsect.bin' }, files, dirs: [...frag.dirs, 'DOS', 'TERM', 'TERM\\DOWNLOAD'] }, ROOT);
fs.rmSync(tmp, { recursive: true, force: true });

// ---- the phone line and the Host Link ("the browser" offers pak0.pak)
const ex = REAL ? new PhoneExchange() : new PhoneExchange({ lineRate: RATE });
let picks = 0, sentBytes = 0, dropAt = ABORT_AT;
const host = new HostLink({
  pickFiles: async () => { picks++; return [{ name: 'pak0.pak', data: new Uint8Array(data), mtime: 878862240 }]; },
  onStatus: (s) => { const m = s.match(/sending .*: (\d+) \//); if (m) sentBytes = +m[1]; },
});
ex.register('555-0100', host);
const pc = await boot({ rom: B('rom.bin'), hd: img, phone: ex, phoneNumber: '555-2000' });
if (!REAL) pc.machine.com2.baudOverride = RATE;

const has = (t) => pc.hasText(t);
async function run(ms, pred, step = 5) {
  const end = pc.timeMs + ms;
  let n = 0;
  while (pc.timeMs < end) {
    pc.machine.runFor(step);
    host.tick(pc.timeMs);
    if (dropAt && sentBytes >= dropAt && host.leg) { console.log(`     dropping the line at ${sentBytes} bytes`); dropAt = 0; host.hangup(); }
    if (pred && pred()) return true;
    if (++n % 200 === 0) await new Promise((r) => setImmediate(r));
  }
  return pred ? !!pred() : true;
}
const screenLog = () => pc.screen().split('\n').filter((l) => l.trim()).map((l) => '     | ' + l).join('\n');
const shot = async (f) => { await pc.png(path.join(OUT, f)); console.log(`     screenshot ${path.join(OUT, f)}`); };
function readHost(p) {
  try { const im = pc.machine.ata.img; const fr = new FatReader(Buffer.from(im.buffer, im.byteOffset, im.length)); const e = fr.lookup(p); return e ? Buffer.from(fr.readFile(e)) : null; }
  catch { return null; }
}

check(await run(20000, () => has('C:\\>')), 'DOS prompt');
async function getpak(label) {
  pc.type('C:\\GAMES\\HEXEN2\\GETPAK\r');
  check(await run(10000, () => has('Press any key')), `${label}: GETPAK explains and waits`);
  await shot('getpak-intro.png');
  pc.type(' ');
  check(await run(60000, () => has('ARM-DOS HOST LINK') && has('Your choice')), `${label}: TERM dials the Host Link, its menu`);
  check(await run(60000, () => has('ZMODEM')), `${label}: D -> the browser offers pak0.pak -> ZMODEM download`);
  await run(3000);
  await shot('getpak-transfer.png');
}

const t0 = performance.now(), e0 = pc.timeMs;
await getpak('call 1');
const done = () => has('C:\\GAMES\\HEXEN2>') || has('Type GETPAK') || has('ready') || has('again');
if (ABORT_AT) {
  check(await run(3600e3, done, 20), 'the broken call ends; GETPAK says how to continue');
  console.log(screenLog());
  const part = readHost('GAMES\\HEXEN2\\DATA1\\PAK0.PAK');
  console.log(`     partial PAK0.PAK: ${part ? part.length : 0} bytes`);
  pc.type('CLS\r'); await run(500);
  await getpak('call 2');
}
check(await run(Math.max(600e3, data.length / (RATE / 10) * 1500), done, 20), 'the transfer ends, TERM hangs up, INSTALL runs');
const emuS = (pc.timeMs - e0) / 1000, hostS = (performance.now() - t0) / 1000;
await shot('getpak-done.png');
console.log(screenLog());
const got = readHost('GAMES\\HEXEN2\\DATA1\\PAK0.PAK');
check(got && Buffer.compare(got, data) === 0, `C:\\GAMES\\HEXEN2\\DATA1\\PAK0.PAK arrived intact (${got ? got.length : 0} of ${data.length} bytes)`);
if (whole) check(has('Hexen II is ready'), 'INSTALL: the received PAK0.PAK is the demo (CRC-32 good)');
else check(has('not') || has('again'), 'INSTALL: H2CHECK refuses a file that is not the demo pak');
console.log(`     ${data.length} bytes at ${RATE} bps: ${emuS.toFixed(0)} s emulated (${(data.length / emuS).toFixed(0)} bytes/s), ${hostS.toFixed(0)} s host; ` +
  `at 14,400 bps that is about ${(data.length / 1400 / 3600).toFixed(1)} hours`);
console.log(failures ? `${failures} FAILED` : 'all passed');
process.exit(failures ? 1 : 0);
