#!/usr/bin/env node
// tools/fnt2c.mjs - GEM/3 system fonts (.FUL + .HDR, the ASCII sources of the
// screen drivers' fonts, Caldera GPL release) -> C source for the ARM VDI.
//
//   node tools/fnt2c.mjs > vdi/fonts.c
//
// Does what DRI's VFNTCNV.C did (strike form: all glyphs side by side, rows of
// form_width bytes, leftmost pixel in bit 7; offset table in pixels), but
// emits C structures instead of RASM86 source.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const DIR = path.join(HERE, '../orig/vdi/fonts');

function readFul(name) {
  const L = fs.readFileSync(path.join(DIR, name), 'latin1').split('\n').map((s) => s.trim());
  let i = 0;
  const fname = L[i++], count = +L[i++], height = +L[i++], formPixels = +L[i++];
  const cw = formPixels / count;
  let bytesPl = formPixels / 8; bytesPl = ((bytesPl + 1) >> 1) << 1;
  const form = new Uint8Array(bytesPl * height);
  for (let c = 0; c < count; c++) {
    i++;                                   // glyph number line
    for (let y = 0; y < height; y++) {
      const row = L[i++] || '';
      for (let x = 0; x < cw; x++) if (row[x] === '1') {
        const dx = c * cw + x;
        form[y * bytesPl + (dx >> 3)] |= 0x80 >> (dx & 7);
      }
    }
  }
  return { fname, count, height, cw, bytesPl, form };
}

function readHdr(name) {
  const t = fs.readFileSync(path.join(DIR, name), 'latin1').split(/\s+/).filter(Boolean);
  const v = (k) => (t[k].startsWith('0x') ? parseInt(t[k], 16) : +t[k]);
  return {
    id: v(0), point: v(1), name: t[2], first: v(3), last: v(4), top: v(5), ascent: v(6), half: v(7),
    descent: v(8), bottom: v(9), maxcw: v(10), maxcellw: v(11), loff: v(12), roff: v(13), thick: v(14),
    ul: v(15), lighten: v(16), skew: v(17), flags: v(18), formw: v(19), formh: v(20),
  };
}

let out = `/*
 * fonts.c - GEM system fonts for the ARM-DOS VDI.  GENERATED by
 * tools/fnt2c.mjs from the GEM/3 screen driver font sources (FONTS/SOURCE/
 * *.FUL, *FUL.HDR; Copyright 1987 Digital Research, released under the GNU
 * GPL v2 by Caldera Thin Clients, 1999).  Do not edit.
 */
#include "vdi.h"

`;
const fonts = [
  ['6x6.ful', '6x6ful.hdr', 'f6x6'],
  ['8x8.ful', '8x8ful.hdr', 'f8x8'],
  ['8x14.ful', '8x14ful.hdr', 'f8x14'],
  ['8x16.ful', '8x16ful.hdr', 'f8x16'],
];
for (const [ful, hdr, id] of fonts) {
  const f = readFul(ful), h = readHdr(hdr);
  const n = h.last - h.first + 1;
  if (n !== f.count) throw new Error(`${ful}: ${f.count} glyphs, header says ${n}`);
  out += `static const UWORD ${id}_off[${n + 1}] = {`;
  for (let c = 0; c <= n; c++) out += (c % 16 ? ' ' : '\n\t') + c * f.cw + ',';
  out += `\n};\nstatic const UBYTE ${id}_dat[${f.form.length}] = {`;
  for (let k = 0; k < f.form.length; k++) out += (k % 16 ? ' ' : '\n\t') + '0x' + f.form[k].toString(16).padStart(2, '0') + ',';
  out += `\n};\n`;
  out += `struct font_head ${id} = {
\t${h.id}, ${h.point}, "${h.name}",
\t${h.first}, ${h.last}, ${h.top}, ${h.ascent}, ${h.half}, ${h.descent}, ${h.bottom},
\t${h.maxcw}, ${h.maxcellw}, ${h.loff}, ${h.roff}, ${h.thick}, ${h.ul},
\t0x${h.lighten.toString(16)}, 0x${h.skew.toString(16)}, 0x${h.flags.toString(16)},
\t0, (UWORD *)${id}_off, (UBYTE *)${id}_dat, ${f.bytesPl}, ${f.height},
\t0, 0, 0, 0, 0, 0, {0}
};

`;
}
out += `struct font_head *font_top = &f8x8;

/* The fonts of one screen: the 8 point (small) system font, then the 10
 * point one (the default), as the GEM/3 drivers linked them. */
struct font_head *fonts_for(WORD cell_height)
{
	struct font_head *small, *big;

	switch (cell_height)
	{
	case 14: small = &f6x6; big = &f8x14; break;
	case 16: small = &f8x8; big = &f8x16; break;
	default: small = &f6x6; big = &f8x8; break;
	}
	if (small == &f8x8)		/* the 8x8 face as the small font */
	{
	  f8x8.point = 8;
	  f8x8.flags = MONOSPACE;
	}
	small->next_font = big;
	big->next_font = 0;
	return font_top = small;
}
`;
process.stdout.write(out);
