#!/usr/bin/env node
// tools/pat2c.mjs - GEM/3 screen driver fill patterns (COMMON/LORESPAT.A86,
// HIRESPAT.A86, Caldera GPL release) and the marker tables (DEVDATA.IBM /
// DEVDATA.HRC) -> C tables for the ARM VDI.   node tools/pat2c.mjs > vdi/patdata.c
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ASM = path.join(HERE, '../orig/vdi/asm');

function parse(file) {
  // label -> array of words (following dw lines up to the next label)
  const res = {};
  let cur = null;
  for (let line of fs.readFileSync(path.join(ASM, file), 'latin1').split('\n')) {
    line = line.replace(/;.*/, '').trim();
    if (!line) continue;
    const m = line.match(/^([A-Za-z_]\w*)\s*:?\s+(dw|rw|db)\s+(.*)$/i);
    let body;
    if (m) { cur = m[1].toLowerCase(); res[cur] = []; body = [m[2], m[3]]; }
    else {
      const d = line.match(/^(dw|rw|db)\s+(.*)$/i);
      if (!d) { cur = null; continue; }
      body = [d[1], d[2]];
    }
    if (!cur || body[0].toLowerCase() !== 'dw') continue;
    for (let v of body[1].split(',')) {
      v = v.trim().toLowerCase();
      if (!v) continue;
      let n;
      if (v.endsWith('h')) n = parseInt(v.slice(0, -1), 16);
      else if (v.endsWith('b')) n = parseInt(v.slice(0, -1), 2);
      else n = parseInt(v, 10);
      if (Number.isNaN(n)) continue;
      res[cur].push(n & 0xffff);
    }
  }
  return res;
}

const arr = (name, a) => `static const UWORD ${name}[${a.length}] = {` +
  a.map((v, i) => (i % 8 ? ' ' : '\n\t') + '0x' + v.toString(16).padStart(4, '0') + ',').join('') + '\n};\n';
const sarr = (name, a) => `static const WORD ${name}[${a.length}] = {` +
  a.map((v, i) => (i % 10 ? ' ' : '\n\t') + ((v << 16) >> 16) + ',').join('') + '\n};\n';

let out = `/*
 * patdata.c - fill patterns and marker shapes of the GEM/3 screen drivers,
 * GENERATED by tools/pat2c.mjs from LORESPAT.A86 / HIRESPAT.A86 and
 * DEVDATA.IBM / DEVDATA.HRC (Copyright 1987 Digital Research; GNU GPL v2,
 * Caldera Thin Clients 1999).  Do not edit.
 */
#include "vdi.h"

`;
for (const [tag, file] of [['lo', 'lorespat.a86'], ['hi', 'hirespat.a86']]) {
  const p = parse(file);
  for (const k of ['oempat', 'dither', 'hatch0', 'hatch1']) out += arr(`${tag}_${k}`, p[k]);
  out += `static const WORD ${tag}_masks[4] = { ${p.oemmskpa[0]}, ${p.dithrmsk[0]}, ${p.hat_0_ms[0]}, ${p.hat_1_ms[0]} };\n`;
  out += arr(`${tag}_mform`, [...p.mxhot.slice(0, 1), ...p.myhot.slice(0, 1), ...p.mmask, ...p.mform]);
}
// line styles and the user pattern are the same in both files
const lo = parse('lorespat.a86');
out += `const WORD line_sty_def[6] = { ${lo.line_sty.map((v) => '(WORD)0x' + v.toString(16)).join(', ')} };\n`;
out += `const WORD ud_patrn_def[16] = { ${lo.ud_patrn.slice(0, 16).map((v) => '(WORD)0x' + v.toString(16)).join(', ')} };\n\n`;
for (const [tag, file] of [['lo', 'devdata.ibm'], ['hi', 'devdata.hrc']]) {
  const p = parse(file);
  for (const k of ['m_dot', 'm_plus', 'm_star', 'm_square', 'm_cross', 'm_dmnd']) out += sarr(`${tag}_${k}`, p[k]);
}
out += `
WORD *DITHER_P, *HATCH0_P, *HATCH1_P, *OEMPAT_P;
WORD DITHRMSK, HAT_0_MSK, HAT_1_MSK, OEMMSKPAT;
WORD SOLID = (WORD)0xffff, HOLLOW = 0;
WORD m_dot[16], m_plus[16], m_star[24], m_square[16], m_cross[16], m_dmnd[16];
WORD def_mform[2 + 32];

#define CP(d, s) memcpy(d, s, sizeof(s))
extern void *memcpy(void *, const void *, unsigned long);

void pattern_init(WORD hires)
{
	if (hires)
	{
	  DITHER_P = (WORD *)hi_dither; HATCH0_P = (WORD *)hi_hatch0;
	  HATCH1_P = (WORD *)hi_hatch1; OEMPAT_P = (WORD *)hi_oempat;
	  OEMMSKPAT = hi_masks[0]; DITHRMSK = hi_masks[1];
	  HAT_0_MSK = hi_masks[2]; HAT_1_MSK = hi_masks[3];
	  CP(m_dot, hi_m_dot); CP(m_plus, hi_m_plus); CP(m_star, hi_m_star);
	  CP(m_square, hi_m_square); CP(m_cross, hi_m_cross); CP(m_dmnd, hi_m_dmnd);
	  CP(def_mform, hi_mform);
	}
	else
	{
	  DITHER_P = (WORD *)lo_dither; HATCH0_P = (WORD *)lo_hatch0;
	  HATCH1_P = (WORD *)lo_hatch1; OEMPAT_P = (WORD *)lo_oempat;
	  OEMMSKPAT = lo_masks[0]; DITHRMSK = lo_masks[1];
	  HAT_0_MSK = lo_masks[2]; HAT_1_MSK = lo_masks[3];
	  CP(m_dot, lo_m_dot); CP(m_plus, lo_m_plus); CP(m_star, lo_m_star);
	  CP(m_square, lo_m_square); CP(m_cross, lo_m_cross); CP(m_dmnd, lo_m_dmnd);
	  CP(def_mform, lo_mform);
	}
}
`;
process.stdout.write(out);
