#!/usr/bin/env python3
"""mbr2c.py MBR.BIN -o bootrec.c - FDISK's master boot record image
(BOOTREC.ASM: "master_boot_record" = FDBOOT.INC twice, one per fixed disk),
for ARM-DOS made from the assembled ARM MBR code (disk/mbr.S): the code at
0x000, an empty partition table at 0x1BE, 55AA at 0x1FE."""
import sys, argparse
ap = argparse.ArgumentParser()
ap.add_argument('bin')
ap.add_argument('-o', '--out', required=True)
a = ap.parse_args()
code = open(a.bin, 'rb').read()
if len(code) > 440:
    raise SystemExit(f'mbr2c: MBR code is {len(code)} bytes, at most 440 fit')
sector = bytearray(512)
sector[:len(code)] = code
sector[510] = 0x55
sector[511] = 0xAA
rows = []
for i in range(0, 512, 16):
    rows.append('    ' + ''.join('0x%02X,' % x for x in sector[i:i + 16]))
body = '\n'.join(rows)
open(a.out, 'w').write(
    '/* generated by apps/fdisk/tools/mbr2c.py from disk/mbr.S - do not edit */\n'
    '/* ARM-DOS: the master boot record FDISK writes to a disk that has none\n'
    '   (the original: BOOTREC.ASM + FDBOOT.ASM, x86 code) */\n'
    'unsigned char master_boot_record[2][512] = {\n'
    '  {\n' + body + '\n  },\n  {\n' + body + '\n  }\n};\n')
