#!/usr/bin/env python3
"""menubld.py - build-time replacement for Microsoft's binary-only
TOOLS/MENUBLD.EXE (MS-DOS 4.0 CMD/FDISK/MAKEFILE: "menubld fdisk.msg
usa-ms.msg" -> fdiskm.c).

FDISK.MSG is C source: every screen fragment is a string of ^rrcc^ cursor
positions, <HRBOWYNSCI...> attribute/control codes and "Φnnnn" references
(0xE8 + four digits) to the country message file's FDISK section.  MENUBLD
replaces each reference with that message's text (the quotes stripped) and
emits the C file.  This one also:
  - makes every menu string writable (display() stores the Yes/No letters
    into <Y>/<N> in place, which MS C allowed in its data segment);
  - applies --subst OLD=NEW to message texts (ARM-DOS branding).

  python3 menubld.py FDISK.MSG USA-MS.MSG -o fdiskm.c [--subst OLD=NEW ...]
"""
import re, sys, argparse, os

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..', 'mslib', 'tools'))
from msgtab import load_msg, render   # noqa: E402


def c_bytes(b):
    out = ''
    for x in b:
        ch = chr(x)
        if ch in '"\\':
            out += '\\' + ch
        elif 32 <= x < 127:
            out += ch
        else:
            out += '\\%03o' % x
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('menu')
    ap.add_argument('msg')
    ap.add_argument('-o', '--out', required=True)
    ap.add_argument('--section', default='FDISK')
    ap.add_argument('--subst', action='append', default=[])
    a = ap.parse_args()
    sec = load_msg(a.msg)[a.section]
    src = open(a.menu, 'rb').read().replace(b'\r', b'')

    def text(m):
        n = int(m.group(1))
        if n not in sec:
            raise SystemExit(f'menubld: message {n} not in section {a.section}')
        b = render(sec[n])
        for s in a.subst:
            old, new = s.split('=', 1)
            b = b.replace(old.encode('latin-1'), new.encode('latin-1'))
        return c_bytes(b).encode('latin-1')

    src = re.sub(rb'\xe8(\d{4})', text, src)
    # char far *name = "..." ;  ->  static char name_s[] = "..." ; char far *name = name_s;
    names = []

    def decl(m):
        names.append(m.group(1).decode())
        return b'static char ' + m.group(1) + b'_s[] ='
    src = re.sub(rb'char\s+far\s+\*\s*(\w+)\s*=', decl, src)
    tail = '\n/* menubld.py: the pointers FDISK uses */\n' + ''.join(
        f'char far *{n} = {n}_s;\n' for n in names)
    head = (b'/* generated by apps/fdisk/tools/menubld.py from FDISK.MSG and the FDISK\n'
            b'   section of USA-MS.MSG - (c) Microsoft Corp., MIT License - do not edit */\n'
            b'#ifndef far\n#define far\n#endif\n')
    open(a.out, 'wb').write(head + src + tail.encode())


if __name__ == '__main__':
    main()
